/**
 * seed 事实闭包内全部权限码的**运行时**单一清单 —— 权限目录护栏的判据来源。
 *
 * ──────────────────────────────────────────────────────────────────────────
 * 为什么必须在 `src/` 再放一份(而不是直接读 seed)
 *
 * 权限码的事实源是 seed 事实闭包(`prisma/seed.ts` + `permission-catalog.ts`),
 * 但生产运行时**够不到它**:
 *   1. `tsconfig.json` 的 `include` 只有 `src/**\/*.ts` ⇒ `prisma/seed.ts` 不进 `dist/`;
 *   2. `prisma/seed.ts` 自己 `import { … } from '../src/modules/permissions/permission-catalog'`
 *      ⇒ 若 `src/` 反向 import 它就是**循环依赖**,且会把整个 seed 程序拖进 API 进程。
 * 方向恒为 seed → src,不得反向 —— 所以护栏要判「这个码是不是系统拥有的」,
 * 就只能在 `src/` 侧有一份可在运行时读到的清单。
 *
 * ⚠️ 这确实是**第二份清单**,与本目录 CLAUDE.md「禁止另造代码清单」的默认立场相冲。
 * 它被允许的唯一理由是:**它被机器钉死在事实源上**,漂了当场红 ——
 * 与 [`protected-role-codes.ts`](protected-role-codes.ts)(15 个内置角色的 API 删除保护清单,
 * 靠 seed-rbac e2e 漂移哨兵守)是同一范式的镜像件。没有哨兵的第二份清单才是被禁的那种。
 *
 * ──────────────────────────────────────────────────────────────────────────
 * 谁保证这份清单不漂(三段链,每段各有独立执法位)
 *
 *   本文件  ==(A)==  `RBAC_SEED_CATALOG.permissions` 各桶并集
 *                       ==(B)==  typed-AST 扫出的权限码全集
 *                       ==(C)==  seed 后 DB 里的 `permissions` 行
 *
 *   (A)+(B) [`seed-permission-codes.spec.ts`](seed-permission-codes.spec.ts):
 *           直接跟 `scripts/check-permission-catalog-closure.ts`(红区 selfGuard 内)
 *           算出的 typed-AST **全集**逐条对照,两个方向都查。实质提取逻辑在那个受保护文件里,
 *           本清单改漂 / 提取器口径漂,任一侧动了都会红。
 *   (C)     `test/e2e/seed-permission-catalog-runtime.e2e-spec.ts`:
 *           空库 → 实跑 seed → 读 DB 的 `permissions` 表跟本清单对照。
 *           **这一条是源码侧判据代替不了的** —— 运行时经 API 增删权限行不改任何源码,
 *           源码侧闭包判据(#1129)对那种漂移结构性失明。
 *
 * ──────────────────────────────────────────────────────────────────────────
 * 新增权限码时怎么办
 *
 * 照常改 `prisma/seed.ts` 加数组 + 在 `RBAC_SEED_CATALOG.permissions` 加桶,
 * 然后把新码按字典序补进下面的数组。漏补 ⇒ 上面 (A) 当场红并点名,不会静默。
 *
 * 刻意**不**写「恰 N 条」的冻结断言:那种断言每加一个码都要改数字,
 * 改数字的摩擦会诱导人把数字调大了事;真正的锁是「与事实源逐条相等」。
 */

/** seed 事实闭包内的全部权限码,字典序。改动必须与事实源同步,否则漂移哨兵红。 */
export const SEED_PERMISSION_CODES: readonly string[] = Object.freeze([
  'activity-registration.approve.record',
  'activity-registration.cancel.record',
  'activity-registration.create.record',
  'activity-registration.read.record',
  'activity-registration.reject.record',
  'activity-registration.reopen.record',
  'activity-responsibility.override.record',
  'activity-review.read.request',
  'activity-review.return.request',
  'activity.cancel.record',
  'activity.complete.record',
  'activity.create.cross-org',
  'activity.create.record',
  'activity.delete.record',
  'activity.publish.record',
  'activity.settlement-close.record',
  'activity.settlement-final-review.record',
  'activity.settlement-first-review.record',
  'activity.settlement-generate.record',
  'activity.settlement-submit.record',
  'activity.settlement-update-draft.record',
  'activity.update.record',
  'announcement-import.execute.record',
  'announcement-import.preview.record',
  'attachment-config.create.mime',
  'attachment-config.create.size-limit',
  'attachment-config.create.type',
  'attachment-config.delete.mime',
  'attachment-config.delete.size-limit',
  'attachment-config.delete.type',
  'attachment-config.read.mime',
  'attachment-config.read.size-limit',
  'attachment-config.read.type',
  'attachment-config.update.mime',
  'attachment-config.update.size-limit',
  'attachment-config.update.type',
  'attachment.delete.activity',
  'attachment.delete.certificate.other',
  'attachment.delete.certificate.self',
  'attachment.delete.content-file',
  'attachment.delete.content-image',
  'attachment.delete.member.other',
  'attachment.delete.member.self',
  'attachment.update.activity',
  'attachment.update.certificate.other',
  'attachment.update.certificate.self',
  'attachment.update.member.other',
  'attachment.update.member.self',
  'attachment.upload.activity',
  'attachment.upload.certificate.other',
  'attachment.upload.certificate.self',
  'attachment.upload.content-file',
  'attachment.upload.content-image',
  'attachment.upload.member.other',
  'attachment.upload.member.self',
  'attachment.view.activity',
  'attachment.view.certificate.other',
  'attachment.view.certificate.self',
  'attachment.view.member.other',
  'attachment.view.member.self',
  'attendance.approve.sheet',
  'attendance.create.sheet',
  'attendance.delete.sheet',
  'attendance.final-approve.sheet',
  'attendance.final-reject.sheet',
  'attendance.final-return.sheet',
  'attendance.read.sheet',
  'attendance.reject.sheet',
  'attendance.reopen.sheet',
  'attendance.return.sheet',
  'attendance.update.sheet',
  'audit-log.read.entry',
  'authz.action-state.decision',
  'authz.explain-batch.decision',
  'authz.explain.decision',
  'certificate-recognition-policy.create.record',
  'certificate-recognition-policy.delete.record',
  'certificate-recognition-policy.read.record',
  'certificate-recognition-policy.update.record',
  'certificate-standard.create.record',
  'certificate-standard.delete.record',
  'certificate-standard.read.record',
  'certificate-standard.update.record',
  'certificate.create.record',
  'certificate.delete.record',
  'certificate.read.record',
  'certificate.read.sensitive',
  'certificate.reject.record',
  'certificate.update.record',
  'certificate.verify.record',
  'content.create.record',
  'content.delete.record',
  'content.publish.record',
  'content.read.record',
  'content.update.record',
  'contribution.create.rule',
  'contribution.delete.rule',
  'contribution.read.rule',
  'contribution.update.rule',
  'dict.create.item',
  'dict.create.type',
  'dict.delete.item',
  'dict.delete.type',
  'dict.read.item',
  'dict.read.type',
  'dict.update.item',
  'dict.update.type',
  'emergency-contact.create.record',
  'emergency-contact.delete.record',
  'emergency-contact.read.record',
  'emergency-contact.read.sensitive',
  'emergency-contact.update.record',
  'member-department.clear.current',
  'member-department.read.current',
  'member-department.set.current',
  'member-insurance.read.other',
  'member-insurance.review.record',
  'member-portrait.manage.record',
  'member-portrait.read.history',
  'member-profile.create.record',
  'member-profile.read.record',
  'member-profile.read.sensitive',
  'member-profile.update.record',
  'member.bind.account',
  'member.correct.identity',
  'member.create.record',
  'member.delete.record',
  'member.grant.account',
  'member.offboard.record',
  'member.read.record',
  'member.update.record',
  'member.update.status',
  'membership.end.record',
  'membership.list.record',
  'membership.read.record',
  'membership.set.record',
  'membership.transfer.record',
  'meta.resolve.label',
  'notification.create.record',
  'notification.delete.record',
  'notification.publish.record',
  'notification.read.record',
  'notification.replay.wecom',
  'notification.send.sms',
  'notification.update.record',
  'notification.update.template',
  'org.create.node',
  'org.delete.node',
  'org.move.node',
  'org.read.node',
  'org.update.node',
  'position-assignment.create.record',
  'position-assignment.read.history',
  'position-assignment.read.record',
  'position-assignment.revoke.record',
  'position-rule.create.record',
  'position-rule.delete.record',
  'position-rule.read.record',
  'position-rule.update.record',
  'position.create.definition',
  'position.delete.definition',
  'position.read.definition',
  'position.update.definition',
  'rbac.config.reload',
  'rbac.permission.create',
  'rbac.permission.delete',
  'rbac.permission.read',
  'rbac.permission.update',
  'rbac.role-permission.create',
  'rbac.role-permission.delete',
  'rbac.role.create',
  'rbac.role.delete',
  'rbac.role.read',
  'rbac.role.update',
  'rbac.user-role.create',
  'rbac.user-role.delete',
  'rbac.user-role.read',
  'realname-setting.read.singleton',
  'realname-setting.reset.credentials',
  'realname-setting.update.singleton',
  'recruitment-application.evaluate.assessment',
  'recruitment-application.mark.threshold',
  'recruitment-application.promote.member',
  'recruitment-application.promote.single',
  'recruitment-application.read.record',
  'recruitment-application.read.sensitive',
  'recruitment-application.resolve.manual',
  'recruitment-application.review.certificate',
  'recruitment-application.update.record',
  'recruitment-cycle.create.record',
  'recruitment-cycle.read.record',
  'recruitment-cycle.update.record',
  'role-binding.create.record',
  'role-binding.delete.record',
  'role-binding.read.record',
  'role-binding.update.record',
  'service-principal.create.credential',
  'service-principal.create.record',
  'service-principal.read.record',
  'service-principal.revoke.credential',
  'service-principal.update.record',
  'service-principal.update.status',
  'sms-send-log.read.list',
  'sms-setting.read.singleton',
  'sms-setting.reset.credentials',
  'sms-setting.update.singleton',
  'storage-setting.read.singleton',
  'storage-setting.reset.credentials',
  'storage-setting.update.singleton',
  'supervision-assignment.create.record',
  'supervision-assignment.read.record',
  'supervision-assignment.revoke.record',
  'supervision-assignment.update.record',
  'team-insurance-policy.add.member',
  'team-insurance-policy.create.record',
  'team-insurance-policy.delete.record',
  'team-insurance-policy.read.record',
  'team-insurance-policy.remove.member',
  'team-insurance-policy.update.record',
  'team-join-application.evaluate.assessment',
  'team-join-application.join.member',
  'team-join-application.mark.gate',
  'team-join-application.read.record',
  'team-join-cycle.create.record',
  'team-join-cycle.read.record',
  'team-join-cycle.update.record',
  'user.create.account',
  'user.delete.account',
  'user.phone.clear',
  'user.read.account',
  'user.reset.password',
  'user.update.account',
  'user.update.role',
  'user.update.status',
  'user.wechat.clear',
  'user.wecom.clear',
  'wechat-setting.read.singleton',
  'wechat-setting.reset.credentials',
  'wechat-setting.update.singleton',
  'wecom-setting.read.singleton',
  'wecom-setting.reset.credentials',
  'wecom-setting.test.connection',
  'wecom-setting.update.singleton',
]);

export const SEED_PERMISSION_CODE_SET: ReadonlySet<string> = new Set(SEED_PERMISSION_CODES);

/**
 * 该权限码是否由 seed 定义(即「系统拥有」而非管理员自建)。
 *
 * 目录护栏的唯一谓词:删除 / 创建 / 改码三条写路径都读它,不得各自再判一次。
 */
export function isSeedPermissionCode(code: string): boolean {
  return SEED_PERMISSION_CODE_SET.has(code);
}
